CREATE TABLE IF NOT EXISTS `users` (
  `id` mediumint(7) unsigned NOT NULL,
  `username` varchar(20) NOT NULL DEFAULT '',
  `name` varchar(120) NOT NULL DEFAULT '',
  `passhash` varchar(32) NOT NULL DEFAULT '',
  `secret` varchar(20) NOT NULL DEFAULT '',
  `email` varchar(80) NOT NULL DEFAULT '',
  `status` enum('pending','confirmed') NOT NULL DEFAULT 'pending',
  `added` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `last_login` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `last_access` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `editsecret` varchar(20) NOT NULL DEFAULT '',
  `theme` varchar(15) NOT NULL DEFAULT '',
  `info` varchar(120) DEFAULT NULL,
  `acceptpms` enum('yes','friends','no') NOT NULL DEFAULT 'yes',
  `ip` varchar(15) NOT NULL DEFAULT '',
  `class` tinyint(2) unsigned NOT NULL DEFAULT '0',
  `override_class` tinyint(2) unsigned NOT NULL DEFAULT '255',
  `support` enum('no','yes') NOT NULL DEFAULT 'no',
  `supportfor` varchar(100) DEFAULT NULL,
  `avatar` varchar(30) NOT NULL DEFAULT '',
  `telgr` varchar(40) NOT NULL,
  `skype` varchar(40) NOT NULL DEFAULT '',
  `website` varchar(30) NOT NULL DEFAULT '',
  `uploaded` bigint(20) unsigned NOT NULL DEFAULT '0',
  `downloaded` bigint(20) unsigned NOT NULL DEFAULT '0',
  `bonus` decimal(10,1) NOT NULL DEFAULT '0.0',
  `title` varchar(30) NOT NULL DEFAULT '',
  `country` tinyint(3) unsigned NOT NULL DEFAULT '15',
  `notifs` varchar(100) NOT NULL DEFAULT '',
  `modcomment` text,
  `enabled` enum('yes','no') NOT NULL DEFAULT 'yes',
  `parked` enum('yes','no') NOT NULL DEFAULT 'no',
  `hide` enum('yes','no') NOT NULL DEFAULT 'no',
  `avatars` enum('yes','no') NOT NULL DEFAULT 'yes',
  `donor` enum('yes','no') NOT NULL DEFAULT 'no',
  `simpaty` int(10) NOT NULL DEFAULT '0',
  `warned` enum('yes','no') NOT NULL DEFAULT 'no',
  `warneduntil` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `torrentsperpage` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `topicsperpage` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `postsperpage` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `deletepms` enum('yes','no') NOT NULL DEFAULT 'yes',
  `savepms` enum('yes','no') NOT NULL DEFAULT 'no',
  `gender` enum('1','2','3') NOT NULL DEFAULT '3',
  `birthday` date DEFAULT '0000-00-00',
  `passkey` varchar(32) NOT NULL DEFAULT '',
  `language` varchar(10) DEFAULT NULL,
  `invites` smallint(5) NOT NULL DEFAULT '0',
  `invitedby` mediumint(7) NOT NULL DEFAULT '0',
  `invitedroot` mediumint(7) NOT NULL DEFAULT '0',
  `passkey_ip` varchar(15) NOT NULL DEFAULT '',
  `schoutboxpos` enum('yes','no') NOT NULL DEFAULT 'yes',
  `vipuntil` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `oldclass` tinyint(2) NOT NULL DEFAULT '0',
  `comentoff` enum('yes','no') NOT NULL DEFAULT 'yes',
  `lsoff` enum('yes','no') NOT NULL DEFAULT 'yes',
  `hides` enum('yes','no') DEFAULT 'yes',
  `hider` enum('yes','no') DEFAULT 'yes',
  `hiders` enum('yes','no') DEFAULT 'yes',
  `invayted` enum('yes','no') DEFAULT 'yes',
  `invayt` enum('yes','no') DEFAULT 'yes',
  `bonusss` enum('yes','no') DEFAULT 'yes',
  `upluntil` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `admuntil` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `freeuntil` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `briluntil` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `last_upload` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `premiya` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `stops` enum('yes','no') NOT NULL DEFAULT 'no',
  `question` varchar(30) NOT NULL DEFAULT '',
  `donated` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `seeder` smallint(4) unsigned NOT NULL DEFAULT '0',
  `leecher` smallint(4) unsigned NOT NULL DEFAULT '0',
  `announce` enum('yes','no') NOT NULL DEFAULT 'yes',
  `multik` enum('yes','no') DEFAULT 'no',
  `comreliz` tinyint(3) NOT NULL DEFAULT '0',
  `comforum` tinyint(3) NOT NULL DEFAULT '0',
  `topicforum` tinyint(3) NOT NULL DEFAULT '0'
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

ALTER TABLE `users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `username` (`username`),
  ADD UNIQUE KEY `email` (`email`),
  ADD UNIQUE KEY `passhash` (`passhash`),
  ADD UNIQUE KEY `user` (`id`,`status`,`enabled`) USING BTREE,
  ADD UNIQUE KEY `ojidind` (`id`,`avatar`,`warned`,`username`,`title`,`class`,`donor`,`downloaded`,`uploaded`,`enabled`,`parked`,`last_access`) USING BTREE,
  ADD UNIQUE KEY `id_lastaccess` (`id`,`last_access`) USING BTREE,
  ADD UNIQUE KEY `userdetalis` (`id`,`username`,`status`,`class`,`hide`) USING BTREE,
  ADD UNIQUE KEY `staff2` (`status`,`class`,`username`,`id`,`avatar`,`last_access`) USING BTREE,
  ADD UNIQUE KEY `staff1` (`support`,`status`,`username`,`id`,`last_access`,`class`,`supportfor`,`avatar`,`country`) USING BTREE,
  ADD KEY `status_added` (`status`,`added`),
  ADD KEY `ip` (`ip`),
  ADD KEY `uploaded` (`uploaded`),
  ADD KEY `downloaded` (`downloaded`),
  ADD KEY `country` (`country`),
  ADD KEY `last_access` (`last_access`),
  ADD KEY `enabled` (`enabled`),
  ADD KEY `warned` (`warned`),
  ADD KEY `passkey` (`passkey`),
  ADD KEY `bonus` (`bonus`),
  ADD KEY `parked` (`parked`),
  ADD KEY `gender` (`gender`),
  ADD KEY `bonusss` (`bonusss`),
  ADD KEY `stops` (`stops`),
  ADD KEY `premiya` (`premiya`),
  ADD KEY `class_downloaded_added` (`class`,`downloaded`,`added`) USING BTREE,
  ADD KEY `parked_status_class_last` (`parked`,`status`,`class`,`last_access`) USING BTREE,
  ADD KEY `status_last` (`status`,`last_access`) USING BTREE,
  ADD KEY `warned_warneduntil` (`warned`,`warneduntil`) USING BTREE,
  ADD KEY `vipuntil` (`vipuntil`),
  ADD KEY `upluntil` (`upluntil`),
  ADD KEY `admuntil` (`admuntil`),
  ADD KEY `class_down_upl_added` (`class`,`downloaded`,`uploaded`,`added`) USING BTREE,
  ADD KEY `class_down_upl_bonus_added` (`class`,`downloaded`,`uploaded`,`bonus`,`added`) USING BTREE,
  ADD KEY `class_bonus` (`class`,`bonus`) USING BTREE,
  ADD KEY `passkey_last_access` (`passkey`,`last_access`) USING BTREE,
  ADD KEY `status_id` (`status`,`id`) USING BTREE,
  ADD KEY `last_access_class` (`last_access`,`class`) USING BTREE,
  ADD KEY `class_id` (`class`,`id`) USING BTREE,
  ADD KEY `enabled_status_added` (`enabled`,`status`,`added`) USING BTREE;

ALTER TABLE `users`
  MODIFY `id` mediumint(7) unsigned NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=1;
